uploads = []
generated = []

[[outputs]]
id = "oKF14RUxEEHDqBzPCOl97"
uri = "file://flexi-route-final.zip"
type = "unspecified"
title = "flexi-route-final.zip"

[[outputs]]
id = "zibnX2JC0jaew6Gek3nL_"
uri = "file://flexi_v2.zip"
type = "unspecified"
title = "flexi v2.zip"

[[outputs]]
id = "x5vxSKjEruWzrh5p8KmDe"
uri = "file://flexi-v2.zip"
type = "unspecified"
title = "Flexi Route v2"

[[outputs]]
id = "7C4ooWxzflnyDnCFaz_wV"
uri = "file://flexi-route-source.zip"
type = "unspecified"
title = "Flexi Route Source Code"

[[outputs]]
id = "7TzE031mBnMgJJ7_ajV0T"
uri = "file://task8-updated-files.zip"
type = "unspecified"
title = "Task #8 — Updated Files (email.ts + payments.ts)"

[[outputs]]
id = "BZllq5U7xRiO0GM0pogYF"
uri = "file://flexi-route-v3.zip"
type = "unspecified"
title = "Flexi Route v3 — Source Files"

[[outputs]]
id = "GibRjF06eErpspdff1xoj"
uri = "file://flexi-route-updated.zip"
type = "unspecified"
title = "Flexi Route — Updated Files (email.ts + payments.ts)"

[[outputs]]
id = "v8m9Jy8ajS5F2wkJjjmOT"
uri = "file://flexi-route-fixes.zip"
type = "unspecified"
title = "Flexi Route — Bug Fixes (payments.ts + shipments.ts + admin/payments.tsx)"
