uploads = []
generated = []

[[outputs]]
id = "oKF14RUxEEHDqBzPCOl97"
uri = "file://flexi-route-final.zip"
type = "unspecified"
title = "flexi-route-final.zip"

[[outputs]]
id = "zibnX2JC0jaew6Gek3nL_"
uri = "file://flexi_v2.zip"
type = "unspecified"
title = "flexi v2.zip"

[[outputs]]
id = "x5vxSKjEruWzrh5p8KmDe"
uri = "file://flexi-v2.zip"
type = "unspecified"
title = "Flexi Route v2"
